spring.application.name=prestamos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=chn_prestamos;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ChnPass123!}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jackson.default-property-inclusion=non_null
